//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team32App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Team32App.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Menu.
        /// </summary>
        internal static string BackToMainMenu {
            get {
                return ResourceManager.GetString("BackToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        internal static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrases.
        /// </summary>
        internal static string Phrases {
            get {
                return ResourceManager.GetString("Phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need an Accommodation.
        /// </summary>
        internal static string Phrases_Accomodation {
            get {
                return ResourceManager.GetString("Phrases_Accomodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreeing.
        /// </summary>
        internal static string Phrases_Agreeing {
            get {
                return ResourceManager.GetString("Phrases_Agreeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am allergic to…..
        /// </summary>
        internal static string Phrases_Allergic {
            get {
                return ResourceManager.GetString("Phrases_Allergic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to charge my phone.
        /// </summary>
        internal static string Phrases_Charge {
            get {
                return ResourceManager.GetString("Phrases_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am freezing.
        /// </summary>
        internal static string Phrases_Cold {
            get {
                return ResourceManager.GetString("Phrases_Cold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much does that cost?.
        /// </summary>
        internal static string Phrases_Cost {
            get {
                return ResourceManager.GetString("Phrases_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denying.
        /// </summary>
        internal static string Phrases_Denying {
            get {
                return ResourceManager.GetString("Phrases_Denying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need a doctor.
        /// </summary>
        internal static string Phrases_Doctor {
            get {
                return ResourceManager.GetString("Phrases_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t understand.
        /// </summary>
        internal static string Phrases_DoNotUnderstand {
            get {
                return ResourceManager.GetString("Phrases_DoNotUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings.
        /// </summary>
        internal static string Phrases_Greetings {
            get {
                return ResourceManager.GetString("Phrases_Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek Phrases.
        /// </summary>
        internal static string Phrases_Heading {
            get {
                return ResourceManager.GetString("Phrases_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How are you?.
        /// </summary>
        internal static string Phrases_HowAreYou {
            get {
                return ResourceManager.GetString("Phrases_HowAreYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m hungry.
        /// </summary>
        internal static string Phrases_Hungry {
            get {
                return ResourceManager.GetString("Phrases_Hungry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m from....
        /// </summary>
        internal static string Phrases_ImFrom {
            get {
                return ResourceManager.GetString("Phrases_ImFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phrase is pronounced in Greek:.
        /// </summary>
        internal static string Phrases_Info {
            get {
                return ResourceManager.GetString("Phrases_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need a legal help.
        /// </summary>
        internal static string Phrases_Legal {
            get {
                return ResourceManager.GetString("Phrases_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1.
        /// </summary>
        internal static string Phrases_Level1 {
            get {
                return ResourceManager.GetString("Phrases_Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2.
        /// </summary>
        internal static string Phrases_Level2 {
            get {
                return ResourceManager.GetString("Phrases_Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3.
        /// </summary>
        internal static string Phrases_Level3 {
            get {
                return ResourceManager.GetString("Phrases_Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am looking for….
        /// </summary>
        internal static string Phrases_Looking {
            get {
                return ResourceManager.GetString("Phrases_Looking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does _____ mean?.
        /// </summary>
        internal static string Phrases_Mean {
            get {
                return ResourceManager.GetString("Phrases_Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name is....
        /// </summary>
        internal static string Phrases_MyNameIs {
            get {
                return ResourceManager.GetString("Phrases_MyNameIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have a pet.
        /// </summary>
        internal static string Phrases_Pet {
            get {
                return ResourceManager.GetString("Phrases_Pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you repeat that please?.
        /// </summary>
        internal static string Phrases_Repeat {
            get {
                return ResourceManager.GetString("Phrases_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is the Restroom?.
        /// </summary>
        internal static string Phrases_Restroom {
            get {
                return ResourceManager.GetString("Phrases_Restroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you please talk slower?.
        /// </summary>
        internal static string Phrases_Slower {
            get {
                return ResourceManager.GetString("Phrases_Slower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t speak Greek very well..
        /// </summary>
        internal static string Phrases_Speak {
            get {
                return ResourceManager.GetString("Phrases_Speak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you spell that?.
        /// </summary>
        internal static string Phrases_Spell {
            get {
                return ResourceManager.GetString("Phrases_Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        internal static string Phrases_ThankYou {
            get {
                return ResourceManager.GetString("Phrases_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m thirsty.
        /// </summary>
        internal static string Phrases_Thristy {
            get {
                return ResourceManager.GetString("Phrases_Thristy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time is it?.
        /// </summary>
        internal static string Phrases_Time {
            get {
                return ResourceManager.GetString("Phrases_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Level 1 of Greek Phrases!.
        /// </summary>
        internal static string Phrases_Welcome1 {
            get {
                return ResourceManager.GetString("Phrases_Welcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Level 2 of Greek Phrases!.
        /// </summary>
        internal static string Phrases_Welcome2 {
            get {
                return ResourceManager.GetString("Phrases_Welcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Level 3 of Greek Phrases!.
        /// </summary>
        internal static string Phrases_Welcome3 {
            get {
                return ResourceManager.GetString("Phrases_Welcome3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your name?.
        /// </summary>
        internal static string Phrases_YourName {
            get {
                return ResourceManager.GetString("Phrases_YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the English version of this app.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
