//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team32App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GreekPhrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GreekPhrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Team32App.Resources.GreekPhrases", typeof(GreekPhrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χρειάζομαι ένα κατάλυμα
        ///[:Chreiázomai éna katályma:].
        /// </summary>
        internal static string Phrases_Accomodation {
            get {
                return ResourceManager.GetString("Phrases_Accomodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συμφωνώντας
        ///[:Symfonóntas:].
        /// </summary>
        internal static string Phrases_Agreeing {
            get {
                return ResourceManager.GetString("Phrases_Agreeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πρέπει να φορτίσω το τηλέφωνό μου
        ///[:Prépei na fortíso to tiléfonó mou:].
        /// </summary>
        internal static string Phrases_Charge {
            get {
                return ResourceManager.GetString("Phrases_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αρνούμενος
        ///[:Arnoúmenos:].
        /// </summary>
        internal static string Phrases_Denying {
            get {
                return ResourceManager.GetString("Phrases_Denying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χαιρετίσματα
        ///[:Chairetísmata:].
        /// </summary>
        internal static string Phrases_Greetings {
            get {
                return ResourceManager.GetString("Phrases_Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πώς είσαι;
        ///[:Pós eísai?:].
        /// </summary>
        internal static string Phrases_HowAreYou {
            get {
                return ResourceManager.GetString("Phrases_HowAreYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to πεινάω
        ///[:peináo:].
        /// </summary>
        internal static string Phrases_Hungry {
            get {
                return ResourceManager.GetString("Phrases_Hungry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είμαι από...
        ///[:Eímai apó...:].
        /// </summary>
        internal static string Phrases_ImFrom {
            get {
                return ResourceManager.GetString("Phrases_ImFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χρειάζομαι νομική βοήθεια
        ///[:Chreiázomai nomikí voítheia:].
        /// </summary>
        internal static string Phrases_Legal {
            get {
                return ResourceManager.GetString("Phrases_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το όνομά μου είναι...
        ///[:To ónomá mou eínai...:].
        /// </summary>
        internal static string Phrases_MyNameIs {
            get {
                return ResourceManager.GetString("Phrases_MyNameIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to έχω ενα κατοικίδιο
        ///[:écho ena katoikídio:].
        /// </summary>
        internal static string Phrases_Pet {
            get {
                return ResourceManager.GetString("Phrases_Pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πού είναι η τουαλέτα?
        ///[:Poú eínai i toualéta?:].
        /// </summary>
        internal static string Phrases_Restroom {
            get {
                return ResourceManager.GetString("Phrases_Restroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ευχαριστώ
        ///[:Efcharistó:].
        /// </summary>
        internal static string Phrases_ThankYou {
            get {
                return ResourceManager.GetString("Phrases_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τι ώρα είναι?
        ///[:Ti óra eínai?:].
        /// </summary>
        internal static string Phrases_Time {
            get {
                return ResourceManager.GetString("Phrases_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πως σε λένε?
        ///[:Pos se léne?:].
        /// </summary>
        internal static string Phrases_YourName {
            get {
                return ResourceManager.GetString("Phrases_YourName", resourceCulture);
            }
        }
    }
}
